INSERT INTO categorie (id, nom, quantite) VALUES (1, 'Keybord', 16);
INSERT INTO categorie (id, nom, quantite) VALUES (2, 'Poly EDGE B30 (IP Pone)', 8);
INSERT INTO categorie (id, nom, quantite) VALUES (3, 'Mouse', 10);
INSERT INTO categorie (id, nom, quantite) VALUES (4, 'Poly CCX 600 (IP Phone)', 2);
INSERT INTO categorie (id, nom, quantite) VALUES (5, 'Keybord Wirless', 2);
INSERT INTO categorie (id, nom, quantite) VALUES (6, 'Stack Cable', 37);
INSERT INTO categorie (id, nom, quantite) VALUES (7, 'Access Point internal', 5);
INSERT INTO categorie (id, nom, quantite) VALUES (8, 'Access Point External', 6);
INSERT INTO categorie (id, nom, quantite) VALUES (9, 'Cable Organizer Office', 7);
INSERT INTO categorie (id, nom, quantite) VALUES (10, 'Dock Station Support (Mouniting kit)', 7);
INSERT INTO categorie (id, nom, quantite) VALUES (11, 'Dock Station PRO', 8);
INSERT INTO categorie (id, nom, quantite) VALUES (12, 'Dock Station OLD', 9);
INSERT INTO categorie (id, nom, quantite) VALUES (13, 'Support equipement Salle server', 9);
INSERT INTO categorie (id, nom, quantite) VALUES (14, 'Panneau de brassage Fiber', 1);
INSERT INTO categorie (id, nom, quantite) VALUES (15, 'Cable Organizer Servere room', 2);
INSERT INTO categorie (id, nom, quantite) VALUES (16, 'Raalonge Server room', 3);
INSERT INTO categorie (id, nom, quantite) VALUES (17, 'cable Screen (tactile)', 89);
INSERT INTO categorie (id, nom, quantite) VALUES (18, 'Cable console old', 4);
INSERT INTO categorie (id, nom, quantite) VALUES (19, 'conveter Fiber to RJ45', 2);
INSERT INTO categorie (id, nom, quantite) VALUES (20, 'Cable TNT', 1);
INSERT INTO categorie (id, nom, quantite) VALUES (21, 'Cable 1M Grey', 231);
INSERT INTO categorie (id, nom, quantite) VALUES (22, 'Cable 0.5M', 15);
INSERT INTO categorie (id, nom, quantite) VALUES (23, 'Cable 1M Green', 2);
INSERT INTO categorie (id, nom, quantite) VALUES (24, 'Cable 1M Jeune', 6);
INSERT INTO categorie (id, nom, quantite) VALUES (25, 'Jartiere LC/LC', 19);
INSERT INTO categorie (id, nom, quantite) VALUES (26, 'JArtiere SC/SC', 11);
INSERT INTO categorie (id, nom, quantite) VALUES (27, 'Cable Network 0.15', 120);
INSERT INTO categorie (id, nom, quantite) VALUES (28, 'Jartiere SC/LC', 6);
INSERT INTO categorie (id, nom, quantite) VALUES (29, 'Converter to usb', 2);
INSERT INTO categorie (id, nom, quantite) VALUES (30, 'SFP Fiber Multimode', 10);
INSERT INTO categorie (id, nom, quantite) VALUES (31, 'SFP RJ45 Multi mode', 9);
INSERT INTO categorie (id, nom, quantite) VALUES (32, 'Support Switch', 7);
INSERT INTO categorie (id, nom, quantite) VALUES (33, 'Carte reseau Voix IP', 1);
INSERT INTO categorie (id, nom, quantite) VALUES (34, 'Téléphone Mitel', 1);
INSERT INTO categorie (id, nom, quantite) VALUES (35, 'OLD PaloAlto', 2);
INSERT INTO categorie (id, nom, quantite) VALUES (36, 'OLD SDWan', 2);
INSERT INTO categorie (id, nom, quantite) VALUES (37, 'Support Desktop', 11);
INSERT INTO categorie (id, nom, quantite) VALUES (38, 'Software Cable (Block SFP)', 2);
INSERT INTO categorie (id, nom, quantite) VALUES (39, 'Cutter', 3);
INSERT INTO categorie (id, nom, quantite) VALUES (40, 'Cablehead', 5);
INSERT INTO categorie (id, nom, quantite) VALUES (41, 'Rallonge Bestek', 3);
INSERT INTO categorie (id, nom, quantite) VALUES (42, 'Cable HDMI 1,5M', 30);
INSERT INTO categorie (id, nom, quantite) VALUES (43, 'CABLE Desplay', 31);
INSERT INTO categorie (id, nom, quantite) VALUES (44, 'Cable VGA', 13);
INSERT INTO categorie (id, nom, quantite) VALUES (45, 'Lecteur de badge', 7);
INSERT INTO categorie (id, nom, quantite) VALUES (46, 'Cable HDMI 5M', 2);
INSERT INTO categorie (id, nom, quantite) VALUES (47, 'Cable HDMI 3M', 2);
INSERT INTO categorie (id, nom, quantite) VALUES (48, 'Poly (IP Phone)', 1);
INSERT INTO categorie (id, nom, quantite) VALUES (49, 'Chargeur router orange', 1);
INSERT INTO categorie (id, nom, quantite) VALUES (50, 'Cable Male female', 13);
INSERT INTO categorie (id, nom, quantite) VALUES (51, 'Rallonge', 11);
INSERT INTO categorie (id, nom, quantite) VALUES (52, 'Couplleur', 34);
INSERT INTO categorie (id, nom, quantite) VALUES (53, 'Chargeur OLD', 6);
INSERT INTO categorie (id, nom, quantite) VALUES (54, 'Chargeur Jabra', 1);
INSERT INTO categorie (id, nom, quantite) VALUES (55, 'Chargeur DockDtation', 4);
INSERT INTO categorie (id, nom, quantite) VALUES (56, 'OLD ClickShare', 1);
INSERT INTO categorie (id, nom, quantite) VALUES (57, "Cable D'allimentation", 58);
INSERT INTO categorie (id, nom, quantite) VALUES (58, 'Cable 0.5M white', 250);
INSERT INTO categorie (id, nom, quantite) VALUES (59, 'Chargeur Scan', 2);
INSERT INTO categorie (id, nom, quantite) VALUES (60, 'Cable Printer local', 16);
INSERT INTO categorie (id, nom, quantite) VALUES (61, 'Allimentation Switch', 4);
INSERT INTO categorie (id, nom, quantite) VALUES (62, 'Laptop HP OLD', 5);